### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by newhoteng**
## "Hello Microverse" Project

In this milestone:
-Added index.html file
-Added styles.css file
-Added test.md file

### CODE REVIEW

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi @newhoteng , 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- Your pull request has a good title and a descriptive summary. ✔
- GitHub flow is used correctly. ✔
- You have good commit messages. ✔


## Required Changes ♻️

- [ ] Please add a `readme file` to your project using [this template](https://github.com/microverseinc/readme-template) and make sure to personalize it based on your project. A readme file in your project not only gives it a professional appearance, but it also tells other people why your project is useful, what they can do with it, and how they can use it.👌😊

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by newhoteng** [comment]
@ridwanediallo I already have a readme file on this repo that conforms to the template https://github.com/newhoteng/Hello-world#readme. Can you please be more specific on what else to add or remove?
Thanks

**Comment by Gambit142** [comment]
> @ridwanediallo I already have a readme file on this repo that conforms to the template https://github.com/newhoteng/Hello-world#readme. Can you please be more specific on what else to add or remove? Thanks

Hi @newhoteng, you need to edit the _**Setup**_, _**Install**_ and _**Usage**_ subsections of the **_Getting Started_** section in the README.md template. You can remove the **_Run Test_** and _**Deployment**_ subsections because they are not needed. Kindly see my review to understand what you can do there. 👍

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @newhoteng 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- The `node_modules` and the `test.md` file was git ignored ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
### I am suggesting these changes in the summary because there are no file changes made to the files that need to be worked on 👍

- [x] Kindly make the following changes to the Getting Started section of your README.md file:
- For the _**Setup**_ subsection, give information that shows how to clone the repository
- For the _**Install**_ subsection, show the ways to install linters you used for the project
- You can remove the _**Usage**_, the _**Deployment**_ and **_Run Test_** subsections because they won't be needed for this project
- For the **_MIT/LICENSE_** section, follow the instructions on the right side of this article https://choosealicense.com/licenses/mit/ to create your LICENSE for the project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by newhoteng** [comment]
@Gambit142 Suggested updates have been made

**Comment by newhoteng** [comment]
completed

**Review by christianbiring1 — APPROVED** [review]
Hi @newhoteng , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
## Highlights
- [ ] Linters checks were used correctly :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
